### ISSUE TITLE
Definir e documentar o escopo do projeto e os principais requisitos.

### ISSUE THREAD

**Issue by jaovr** [jaovr/ExchangeCurrency#4]

**Comment by Brun739** [comment]
sugestões:  Notificações de Taxa de Câmbio
O sistema deve permitir que o usuário defina alertas para quando a taxa de câmbio atingir um valor específico.
O sistema deve enviar uma notificação (por e-mail ou aplicativo) quando a taxa de câmbio atender à condição definida.

Suporte a Múltiplos Idiomas e Moedas
O sistema deve ser capaz de exibir informações em múltiplos idiomas, conforme a localização ou preferência do usuário.
O sistema deve suportar todas as principais moedas globais e realizar a conversão entre elas.

 Segurança
Dados sensíveis, como o histórico de conversões e as preferências de notificações do usuário, devem ser armazenados de forma segura, com criptografia quando necessário.
Se o sistema exigir login, o acesso deve ser protegido por autenticação segura (e.g., autenticação multifatorial).
